-- AlterTable
ALTER TABLE `invoice` ADD COLUMN `booking_id` INTEGER NULL,
    ADD COLUMN `card_payment_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `cash_payment_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `credit_payment_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `deposit_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `discount_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `discount_without_tax_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `is_past_revision` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `past_invoice_id` INTEGER NULL,
    ADD COLUMN `payment_date` DATE NULL,
    ADD COLUMN `segment_num` SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN `service_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `service_without_tax_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `settlement_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `settlement_without_tax_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `total_tax_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `total_without_tax_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    ADD COLUMN `voucher_num` INTEGER NULL,
    MODIFY `status` TINYINT NOT NULL DEFAULT 1,
    MODIFY `total_amount` DECIMAL(12, 0) NOT NULL DEFAULT 0,
    MODIFY `created_staff_id` INTEGER NULL;
