version: "3.8"
services:
  zod-follow-mysql:
    image: mysql:8
    ports:
      - "33061:3306"
    volumes:
      - ./mysql/.data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: zod-follow
      MYSQL_ROOT_PASSWORD: 123456Aa@
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    networks:
      - zod-follow-network
    container_name: zod-follow-mysql

networks:
  zod-follow-network:
